### ISSUE TITLE
Model class method in controller?

### ISSUE THREAD

**Issue by jetaggart** [JordyOne/rantly#1]
https://github.com/JordyOne/rantly/blob/master/app/controllers/relationships_controller.rb#L2

Why is this ActiveRecord model in the controller?

**Comment by JordyOne** [comment]
Laziness.  I just didn’t see it.

**Comment by jetaggart** [comment]
Make sure you review your commits and clean up bad/dead/wrong code. These are things that will raise flags when people are looking through code.

**Comment by JordyOne** [comment]
Gotcha.  My bad. I’ll take a refactor afternoon.  I haven’t really done that, and it seems like something that is necessary

**Comment by jetaggart** [comment]
Please reference this issue when you fix that code.
